class Errors:
  parse_errors: int
  key_errors: int
  other_errors: int

  def __init__(self, perr: int = 0, kerr: int = 0, oerr: int = 0):
    self.parse_errors = perr
    self.key_errors = kerr
    self.other_errors = oerr

  def __str__(self):
    return f'''
              PARSE ERRORS: {self.parse_errors}
              KEY ERRORS: {self.key_errors}
              OTHER ERRORS: {self.other_errors}
            '''

errors = Errors(0, 0, 0)

pages = [
  ('SELECT_from_WORLD_Tutorial', 8),
  ('SELECT_from_Nobel_Tutorial', 14),
  ('The_JOIN_operation', 13),
  ('SELECT_within_SELECT_Tutorial', 5),
  ('SELECT_names', 12),
  ('SELECT_names', 15),
  ('More_JOIN_operations', 12)
]

optimized_asts_for_passing_queries = {}

ref_feature_subsets_with_aliases = {}

ref_feature_subsets_with_common_alias = {}

# KEYWORDS 'AS' AND 'ASC" HAVE BEEN TAKEN OUT OF THE FOLLOWING SET!
mssql_keywords = ['CURRENT_TIMEZONE', 'CURRENT_TIMEZONE_ID', 'DATE_BUCKET', 'DIFFERENCE', 'FORMAT', 'QUOTENAME', 'REPLICATE', 'REVERSE', 'UNICODE', 'SOUNDEX', 'STRING_AGG', 'STRING_ESCAPE', 'SUBSTRING', 'TRANSLATE', 'RAND', 'ISNULL', 'ISNUMERIC', 'LAG', 'LEAD', 'USER_NAME', 'SESSIONPROPERTY', 'CAST', 'CONVERT', 'TRY_CAST', 'TRY_CONVERT', 'PARSE', 'TRY_PARSE', 'ROUND', 'SIGN', 'SUM', 'DATEADD', 'DATEDIFF', 'DATEDIFF_BIG', 'DATENAME', 'DATEPART', 'DATETIMEFROMPARTS', 'DATETIME2FROMPARTS', 'DATETIMEOFFSETFROMPARTS', 'DATETRUNC', 'DAY', 'EOMONTH', 'GETDATE', 'ISDATE', 'SMALLDATETIMEFROMPARTS', 'SWITCHOFFSET', 'SYSUTCDATETIME', 'TIMEFROMPARTS', 'TODATETIMEOFFSET', '', 'GETUTCDATE', 'MONTH', 'YEAR', 'FLOOR', 'MAX', 'MIN', 'ABS', 'AVG', 'CEILING', 'UPPER', 'SUBSTR', 'STUFF', 'STR', 'SPACE', 'PATINDEX', 'REPLACE', 'NCHAR', 'TRIM', 'LTRIM', 'RTRIM', 'LOWER', 'LEN', 'DATALENGTH', 'CHAR', 'CHARINDEX', 'CONCAT', 'CONCAT_WS', 'ADD', 'EXTERNAL', 'PROCEDURE', 'ALL', 'COUNT', 'FETCH', 'PUBLIC', 'ALTER', 'FILE', 'RAISERROR', 'AND', 'FILLFACTOR', 'READ', 'ANY', 'FOR', 'READTEXT', 'FOREIGN', 'RECONFIGURE', 'FREETEXT', 'REFERENCES', 'AUTHORIZATION', 'FREETEXTTABLE', 'REPLICATION', 'BACKUP', 'FROM', 'RESTORE', 'BEGIN', 'FULL', 'RESTRICT', 'BETWEEN', 'FUNCTION', 'RETURN', 'BREAK', 'GOTO', 'REVERT', 'BROWSE', 'GRANT', 'REVOKE', 'BULK', 'GROUP', 'RIGHT', 'BY', 'HAVING', 'ROLLBACK', 'CASCADE', 'HOLDLOCK', 'ROWCOUNT', 'CASE', 'IDENTITY', 'ROWGUIDCOL', 'CHECK', 'IDENTITY_INSERT', 'RULE', 'CHECKPOINT', 'IDENTITYCOL', 'SAVE', 'CLOSE', 'IF', 'SCHEMA', 'CLUSTERED', 'IN', 'SECURITYAUDIT', 'COALESCE', 'INDEX', 'SELECT', 'COLLATE', 'INNER', 'SEMANTICKEYPHRASETABLE', 'COLUMN', 'INSERT', 'SEMANTICSIMILARITYDETAILSTABLE', 'COMMIT', 'INTERSECT', 'SEMANTICSIMILARITYTABLE', 'COMPUTE', 'INTO', 'SESSION_USER', 'CONSTRAINT', 'IS', 'SET', 'CONTAINS', 'JOIN', 'SETUSER', 'CONTAINSTABLE', 'KEY', 'SHUTDOWN', 'CONTINUE', 'KILL', 'SOME', 'CONVERT', 'LEFT', 'STATISTICS', 'CREATE', 'LIKE', 'SYSTEM_USER', 'CROSS', 'LINENO', 'TABLE', 'CURRENT', 'LOAD', 'TABLESAMPLE', 'CURRENT_DATE', 'MERGE', 'TEXTSIZE', 'CURRENT_TIME', 'NATIONAL', 'THEN', 'CURRENT_TIMESTAMP', 'NOCHECK', 'TO', 'CURRENT_USER', 'NONCLUSTERED', 'TOP', 'CURSOR', 'NOT', 'TRAN', 'DATABASE', 'NULL', 'TRANSACTION', 'DBCC', 'NULLIF', 'TRIGGER', 'DEALLOCATE', 'OF', 'TRUNCATE', 'DECLARE', 'OFF', 'TRY_CONVERT', 'DEFAULT', 'OFFSETS', 'TSEQUAL', 'DELETE', 'ON', 'UNION', 'DENY', 'OPEN', 'UNIQUE', 'DESC', 'OPENDATASOURCE', 'UNPIVOT', 'DISK', 'OPENQUERY', 'UPDATE', 'DISTINCT', 'OPENROWSET', 'UPDATETEXT', 'DISTRIBUTED', 'OPENXML', 'USE', 'DOUBLE', 'OPTION', 'USER', 'DROP', 'OR', 'VALUES', 'DUMP', 'ORDER', 'VARYING', 'ELSE', 'OUTER', 'VIEW', 'END', 'OVER', 'WAITFOR', 'ERRLVL', 'PERCENT', 'WHEN', 'ESCAPE', 'PIVOT', 'WHERE', 'EXCEPT', 'PLAN', 'WHILE', 'EXEC', 'PRECISION', 'WITH', 'EXECUTE', 'PRIMARY', 'WITHIN GROUP', 'EXISTS', 'PRINT', 'WRITETEXT', 'EXIT', 'PROC']